export const FETCH_START_NOTICES = 'FETCH_START_NOTICES';
export const FETCH_ERROR_NOTICES = 'FETCH_ERROR_NOTICES';
export const FETCH_SUCCESS_NOTICES = 'FETCH_SUCCESS_NOTICES';
export const SET_NOTICES = "SET_NOTICES"